### ISSUE TITLE
try_stale_if_error disables stale-while-revalidate mechanism

### ISSUE THREAD

**Issue by ronaldploeger** [fgsch/vcl-snippets#1]
Hi Federico, 

As far as I can see your sub 'try_stale_if_error' disables Varnishs 'stale-while-revalidate' mechanism, i.e. for every object out of ttl but within grace no stale object is sent back to the client but a synchronous request is sent to the backend. 

Am I missing something? 

I think the stale-while-revalidate mechanism could be kept intact and and stale-if-error be implemented like this in Varnish 5:

sub vcl_hit {
  if (obj.ttl < 0s && obj.ttl + obj.grace > 0s) {
    set req.http.background-fetch = true;
    return (deliver);
  }
}

sub vcl_backend_response {
  if (beresp.status >= 500 && bereq.http.background-fetch) {
    return (abandon);
  }
}

Do you see anything wrong with this approach?

Best regards,
Ronald

**Comment by fgsch** [comment]
Hi Ronald,

The idea behind the implementation is to go to the backend after the TTL elapses but continue using the stale object if an error is encountered. In this case the grace period becomes the stale-if-error period.

Your code looks correct, though you could simplify it by using `bereq.is_bgfetch`.

Maybe I should provide a different snippet to do what you need though.

Best.

**Comment by ronaldploeger** [comment]
Hi Federico, 

thanks for your answer and for the tip to use "is_bgfetch". 

If I understand you correctly it is intentional that your implementation disables the 'stale-while-revalidate' mechanism and converts it into 'stale-if-error'. If so I think this behaviour (the disable of 'stale-while-revalidate') should be documented. 

My implementation keeps the 'stale-while-revalidate' mechanism and adds 'stale-if-error' on top of it. It feels more natural to me as 

1) it keeps closer to the standard Varnish behaviour
2) it serves a response quicker to the client (albeit stale)
3) the implementation is much simpler especially when using "bereq.is_bgfetch". 

Best regards,
Ronald

**Comment by fgsch** [comment]
The whole idea behind stale-if-error is to serve a stale object if there is an error, otherwise use the fresh response. This might seem counter intuitive at first, but that's the desire here.

Sure, we could change the code to use the stale object by default as you described but it's no longer stale-if-error.

I will add some comments to the snippet to make this clear.

Best.

**Comment by ronaldploeger** [comment]
Thanks for clarifying.
